'use strict';
import modalCallback from './modules/modalCallback';
import toggleMenu from './modules/toggleMenu';
import scrollTop from './modules/scrollTop';
import slider from './modules/slider';
import carousel from './modules/carousel';
modalCallback();
toggleMenu();
scrollTop();
slider();
carousel();
